language: c
sudo: required
env:
  global:
    - RACKET_DIR=~/racket
      TBENCHES="bench/tutorial.fpcore bench/hamming/"
      HERBIE_SEED="0"
      UNIT="raco test src/ infra/"
      INTEGRATION="racket $TRAVIS_BUILD_DIR/infra/travis.rkt --seed '${HERBIE_SEED}' $TBENCHES"
      STABILITY="racket $TRAVIS_BUILD_DIR/infra/travis.rkt $TBENCHES"
      POSITS="racket $TRAVIS_BUILD_DIR/infra/travis.rkt bench/posits.fpcore"
  matrix:
    # separate builds for travis benches and unit tests
    - RACKET_VERSION="7.3" JOB="${UNIT}" INSTALL_SOFTPOSIT=true
    - RACKET_VERSION="7.0" JOB="${INTEGRATION}"
    - RACKET_VERSION="7.2" JOB="${INTEGRATION}"
    - RACKET_VERSION="7.3" JOB="${INTEGRATION}"
    - RACKET_VERSION="7.3" JOB="${POSITS}" INSTALL_SOFTPOSIT=true
    # remember to change the `allow_failures` key below!
    - RACKET_VERSION="7.3" JOB="${STABILITY}"
matrix:
  allow_failures:
    - env: RACKET_VERSION="7.3" JOB="${STABILITY}"
  fast_finish: true
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - test -z "$INSTALL_SOFTPOSIT" || raco pkg install softposit-rkt
  - test -z "$INSTALL_SOFTPOSIT" || racket -e "(dynamic-require 'softposit-rkt #f)"
install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR/src
script:
  - echo ${JOB} && eval ${JOB}
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
