language: c
sudo: required
services:
  - docker
cache:
  directories:
    - docker-images
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="6.3"
      HERBIE_SEED="#(2749829514 1059579101 312104142 915324965 966790849 1349306526)"
    - RACKET_VERSION="6.4"
      HERBIE_SEED="#(2749829514 1059579101 312104142 915324965 966790849 1349306526)"
    - RACKET_VERSION="6.5"
      HERBIE_SEED="#(2749829514 1059579101 312104142 915324965 966790849 1349306526)"
    - RACKET_VERSION="6.5"
      HERBIE_SEED="#f"
matrix:
  allow_failures:
    - env: RACKET_VERSION="6.5"
           HERBIE_SEED="#f"
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - docker load -i docker-images/herbie.image || true
install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR/herbie
  - docker build -t herbie .
script:
  - raco test herbie
  - racket infra/travis.rkt --seed "${HERBIE_SEED}" bench/tutorial.rkt bench/hamming/
before_cache:
  - docker save -o docker-images/herbie.image herbie
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
