language: c
sudo: required
env:
  global:
    - RACKET_DIR=~/racket
      TBENCHES="bench/tutorial.fpcore bench/hamming/"
      HERBIE_SEED="0"
      UNIT="raco test src"
      INTEGRATION="racket $TRAVIS_BUILD_DIR/infra/travis.rkt --seed '${HERBIE_SEED}' $TBENCHES"
      STABILITY="racket $TRAVIS_BUILD_DIR/infra/travis.rkt $TBENCHES"
  matrix:
    # separate builds for travis benches and unit tests
    - RACKET_VERSION="6.9"
      JOB="${UNIT}"
    - RACKET_VERSION="6.11"
      JOB="${UNIT}"
    - RACKET_VERSION="7.0"
      JOB="${UNIT}"
    - RACKET_VERSION="6.9"
      JOB="${INTEGRATION}"
    - RACKET_VERSION="6.11"
      JOB="${INTEGRATION}"
    - RACKET_VERSION="7.0"
      JOB="${INTEGRATION}"
    # remember to change the `allow_failures` key below!
    - RACKET_VERSION="7.0"
      JOB="${STABILITY}"
matrix:
  allow_failures:
    - env: RACKET_VERSION="7.0"
           JOB="${STABILITY}"
before_install:
  - wget https://homes.cs.washington.edu/~dthien/assets/files/softposit.so -P lib
  - export LD_LIBRARY_PATH=$(pwd)/lib/:$LD_LIBRARY_PATH
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
install:
  - raco pkg install --auto $TRAVIS_BUILD_DIR/src
script:
  - echo ${JOB} && eval ${JOB}
notifications:
  slack:
    secure: QB8ib/gxZWZ8rY9H54BktIgx8LfjdqabSAkmWip0VHlUhrh2ULG566XgmB5h75eNzCil2cw76ma5wfSC0MNIQ1iDHKCxAgTE0+gcPcZAYGfucQ28sKGBG2wcuJfvBLG6lVDxj+luGUh3XohouTLYI9cg509JBgTgpcrXVexYAaE=
