[package]
name = "rival-herbie"
version = "0.1.0"
edition = "2021"

[dependencies]
rival = { git = "https://github.com/herbie-fp/rival3" }
libc = "0.2"
rug = "1.19"
lazy_static = "1.4"
gmp-mpfr-sys = "1.6"

[lib]
crate-type = ["cdylib"]
